[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
fuzz = { runs = 1000, max_test_rejects = 65536 }
invariant = { runs = 256, depth = 15 }

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 512, depth = 25 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
